vlib work
vlog -sv -work ./work ../package/mul_pkg.sv
vlog -sv -work ./work ../common/counter.sv
vlog -sv -work ./work ../common/FA.sv
vlog -sv -work ./work ../common/csa.sv
vlog -sv -work ./work ../common/rounder.sv
vlog -sv -work ./work ../rtl/booth_encoder.sv
vlog -sv -work ./work ../rtl/multiplicand_reg.sv
vlog -sv -work ./work ../rtl/pp_carry_shift_reg.sv
vlog -sv -work ./work ../rtl/pp_gen.sv
vlog -sv -work ./work ../mul_datapath.sv
vlog -sv -work ./work ../tb/mul_tb.sv
vsim -t 1ns -voptargs=+acc=npr work.mul_tb
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group {Top Level} /mul_tb/clk
add wave -noupdate -expand -group {Top Level} /mul_tb/rst_n
add wave -noupdate -expand -group {Top Level} /mul_tb/start
add wave -noupdate -expand -group {Top Level} /mul_tb/done
add wave -noupdate -expand -group {Top Level} -radix decimal /mul_tb/multiplicand_int
add wave -noupdate -expand -group {Top Level} -radix decimal /mul_tb/multiplier_int
add wave -noupdate -expand -group {Top Level} -radix decimal /mul_tb/product_rounded_int
add wave -noupdate -expand -group {Top Level} -radix decimal -childformat {{{/mul_tb/product_int[15]} -radix binary} {{/mul_tb/product_int[14]} -radix binary} {{/mul_tb/product_int[13]} -radix binary} {{/mul_tb/product_int[12]} -radix binary} {{/mul_tb/product_int[11]} -radix binary} {{/mul_tb/product_int[10]} -radix binary} {{/mul_tb/product_int[9]} -radix binary} {{/mul_tb/product_int[8]} -radix binary} {{/mul_tb/product_int[7]} -radix binary} {{/mul_tb/product_int[6]} -radix binary} {{/mul_tb/product_int[5]} -radix binary} {{/mul_tb/product_int[4]} -radix binary} {{/mul_tb/product_int[3]} -radix binary} {{/mul_tb/product_int[2]} -radix binary} {{/mul_tb/product_int[1]} -radix binary} {{/mul_tb/product_int[0]} -radix binary}} -subitemconfig {{/mul_tb/product_int[15]} {-height 15 -radix binary} {/mul_tb/product_int[14]} {-height 15 -radix binary} {/mul_tb/product_int[13]} {-height 15 -radix binary} {/mul_tb/product_int[12]} {-height 15 -radix binary} {/mul_tb/product_int[11]} {-height 15 -radix binary} {/mul_tb/product_int[10]} {-height 15 -radix binary} {/mul_tb/product_int[9]} {-height 15 -radix binary} {/mul_tb/product_int[8]} {-height 15 -radix binary} {/mul_tb/product_int[7]} {-height 15 -radix binary} {/mul_tb/product_int[6]} {-height 15 -radix binary} {/mul_tb/product_int[5]} {-height 15 -radix binary} {/mul_tb/product_int[4]} {-height 15 -radix binary} {/mul_tb/product_int[3]} {-height 15 -radix binary} {/mul_tb/product_int[2]} {-height 15 -radix binary} {/mul_tb/product_int[1]} {-height 15 -radix binary} {/mul_tb/product_int[0]} {-height 15 -radix binary}} /mul_tb/product_int
add wave -noupdate -expand -group Datapath -radix decimal /mul_tb/mul_datapath_instance/multiplicand_i
add wave -noupdate -expand -group Datapath -radix decimal /mul_tb/mul_datapath_instance/multiplier_i
add wave -noupdate -expand -group Datapath -radix decimal /mul_tb/mul_datapath_instance/product_o
add wave -noupdate -expand -group Datapath /mul_tb/mul_datapath_instance/product_rounded_o
add wave -noupdate -expand -group {Multiplicand Register} -radix decimal /mul_tb/mul_datapath_instance/multiplicand_reg_instance/din
add wave -noupdate -expand -group {Multiplicand Register} -radix decimal /mul_tb/mul_datapath_instance/multiplicand_reg_instance/dout
add wave -noupdate -expand -group {Multiplicand Register} /mul_tb/mul_datapath_instance/multiplicand_reg_instance/load
add wave -noupdate -expand -group {PP register} -radix binary -childformat {{{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[15]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[14]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[13]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[12]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[11]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[10]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[9]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[8]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[7]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[6]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[5]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[4]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[3]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[2]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[1]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[0]} -radix decimal}} -subitemconfig {{/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[15]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[14]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[13]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[12]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[11]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[10]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[9]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[8]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[7]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[6]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[5]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[4]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[3]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[2]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[1]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp[0]} {-height 15 -radix decimal}} /mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/pp
add wave -noupdate -expand -group {PP register} -radix binary /mul_tb/mul_datapath_instance/pp_carry_shift_reg_instance/carry
add wave -noupdate -expand -group {Booth encoder} -radix binary /mul_tb/mul_datapath_instance/booth_encoder_instance/multiplier_in
add wave -noupdate -expand -group {Booth encoder} /mul_tb/mul_datapath_instance/booth_encoder_instance/pp_sel
add wave -noupdate -expand -group {Booth encoder} /mul_tb/mul_datapath_instance/booth_encoder_instance/neg
add wave -noupdate -expand -group {PP Generator} /mul_tb/mul_datapath_instance/pp_gen_instance/booth_sel
add wave -noupdate -expand -group {PP Generator} /mul_tb/mul_datapath_instance/pp_gen_instance/neg_value
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/multiplicand_in
add wave -noupdate -expand -group {PP Generator} -radix binary -childformat {{{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[10]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[9]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[8]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[7]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[6]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[5]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[4]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[3]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[2]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[1]} -radix decimal} {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[0]} -radix decimal}} -subitemconfig {{/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[10]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[9]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[8]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[7]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[6]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[5]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[4]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[3]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[2]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[1]} {-height 15 -radix decimal} {/mul_tb/mul_datapath_instance/pp_gen_instance/pp_out[0]} {-height 15 -radix decimal}} /mul_tb/mul_datapath_instance/pp_gen_instance/pp_out
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/PP_2
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP_2
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/PP_3
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP_3
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/PP_4
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP_4
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/PP_5
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP_5
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/PP_6
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP_6
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/PP_7
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP_7
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/PP_8
add wave -noupdate -expand -group {PP Generator} -radix binary /mul_tb/mul_datapath_instance/pp_gen_instance/not_PP_8
add wave -noupdate -expand -group {Adder Out} -radix binary -childformat {{{/mul_tb/mul_datapath_instance/sum_out[16]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[15]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[14]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[13]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[12]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[11]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[10]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[9]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[8]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[7]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[6]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[5]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[4]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[3]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[2]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[1]} -radix binary} {{/mul_tb/mul_datapath_instance/sum_out[0]} -radix binary}} -subitemconfig {{/mul_tb/mul_datapath_instance/sum_out[16]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[15]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[14]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[13]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[12]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[11]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[10]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[9]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[8]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[7]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[6]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[5]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[4]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[3]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[2]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[1]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/sum_out[0]} {-height 15 -radix binary}} /mul_tb/mul_datapath_instance/sum_out
add wave -noupdate -expand -group CSA /mul_tb/mul_datapath_instance/csa_instance/WIDTH
add wave -noupdate -expand -group CSA -radix binary /mul_tb/mul_datapath_instance/csa_instance/multiplicand_in
add wave -noupdate -expand -group CSA -radix binary -childformat {{{/mul_tb/mul_datapath_instance/csa_instance/pp_in[10]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[9]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[8]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[7]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[6]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[5]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[4]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[3]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[2]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[1]} -radix binary} {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[0]} -radix binary}} -subitemconfig {{/mul_tb/mul_datapath_instance/csa_instance/pp_in[10]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[9]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[8]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[7]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[6]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[5]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[4]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[3]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[2]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[1]} {-height 15 -radix binary} {/mul_tb/mul_datapath_instance/csa_instance/pp_in[0]} {-height 15 -radix binary}} /mul_tb/mul_datapath_instance/csa_instance/pp_in
add wave -noupdate -expand -group CSA -radix binary /mul_tb/mul_datapath_instance/csa_instance/carry_in
add wave -noupdate -expand -group CSA -radix binary /mul_tb/mul_datapath_instance/csa_instance/sum_out
add wave -noupdate -expand -group CSA -radix binary /mul_tb/mul_datapath_instance/csa_instance/carry_out
add wave -noupdate /mul_tb/mul_datapath_instance/counter_instance/counter
vcd file ../waves/test_mul.vcd
vcd add -r mul_tb/*
vcd add -r mul_pkg/*
run 20 us
quit
